/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "transfer.h"

bool_t
xdr_file_data (XDR *xdrs, file_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->data, MAX_DATA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}
